// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOzFXMyIv4_XFp0fKAzq13flAniQxxgGY',
    appId: '1:359743798502:web:0b5645b429457fe05b4f27',
    messagingSenderId: '359743798502',
    projectId: 'laundry-mate-e2dca',
    authDomain: 'laundry-mate-e2dca.firebaseapp.com',
    storageBucket: 'laundry-mate-e2dca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdrQlvvjqZi08eUqCQa8KOelb9wkynpw',
    appId: '1:359743798502:android:322a80460d44c89a5b4f27',
    messagingSenderId: '359743798502',
    projectId: 'laundry-mate-e2dca',
    storageBucket: 'laundry-mate-e2dca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsMt_SqYj_uQ6QiJndi3kEE573QIZQVVk',
    appId: '1:359743798502:ios:08ade1fa04b3eebb5b4f27',
    messagingSenderId: '359743798502',
    projectId: 'laundry-mate-e2dca',
    storageBucket: 'laundry-mate-e2dca.firebasestorage.app',
    iosBundleId: 'com.example.laundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsMt_SqYj_uQ6QiJndi3kEE573QIZQVVk',
    appId: '1:359743798502:ios:08ade1fa04b3eebb5b4f27',
    messagingSenderId: '359743798502',
    projectId: 'laundry-mate-e2dca',
    storageBucket: 'laundry-mate-e2dca.firebasestorage.app',
    iosBundleId: 'com.example.laundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOzFXMyIv4_XFp0fKAzq13flAniQxxgGY',
    appId: '1:359743798502:web:12ace3e00cd206b65b4f27',
    messagingSenderId: '359743798502',
    projectId: 'laundry-mate-e2dca',
    authDomain: 'laundry-mate-e2dca.firebaseapp.com',
    storageBucket: 'laundry-mate-e2dca.firebasestorage.app',
  );
}
